[package]
name = "raytracer"
version = "0.1.0"
edition = "2021"

[dependencies]
assert_approx_eq = "1.1.0"
image = "0.25.5"
rand = "0.9.0"
rand_xoshiro = "0.7.0"

[lints.clippy]
pedantic = {level= "warn", priority=-1} 
similar_names = "allow"
many_single_char_names = "allow"
